-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 18:44:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema QuizMYSQL
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `QuizMYSQL` ;

-- -----------------------------------------------------
-- Schema QuizMYSQL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QuizMYSQL` DEFAULT CHARACTER SET utf8 ;
USE `QuizMYSQL` ;

-- -----------------------------------------------------
-- Table `QuizMYSQL`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuizMYSQL`.`answer` ;

CREATE TABLE IF NOT EXISTS `QuizMYSQL`.`answer` (
  `idAnswer` INT(45) NOT NULL,
  `answer` VARCHAR(45) NOT NULL,
  `expected` TINYINT NOT NULL,
  `selected` TINYINT NULL,
  `question_idquestion` INT NOT NULL,
  `quizID` INT NULL,
  `studentID` INT NULL,
  INDEX `fk_answer_question_idx` (`question_idquestion` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question`
    FOREIGN KEY (`question_idquestion`)
    REFERENCES `QuizMYSQL`.`question` (`idquestion`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuizMYSQL`.`qp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuizMYSQL`.`qp` ;

CREATE TABLE IF NOT EXISTS `QuizMYSQL`.`qp` (
  `poolid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`poolid`),
  UNIQUE INDEX `poolid_UNIQUE` (`poolid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuizMYSQL`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuizMYSQL`.`question` ;

CREATE TABLE IF NOT EXISTS `QuizMYSQL`.`question` (
  `idquestion` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(45) NOT NULL,
  `points` FLOAT NOT NULL,
  `qp_poolid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idquestion`),
  INDEX `fk_question_qp1_idx` (`qp_poolid` ASC) VISIBLE,
  UNIQUE INDEX `idquestion_UNIQUE` (`idquestion` ASC) VISIBLE,
  CONSTRAINT `fk_question_qp1`
    FOREIGN KEY (`qp_poolid`)
    REFERENCES `QuizMYSQL`.`qp` (`poolid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuizMYSQL`.`quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuizMYSQL`.`quiz` ;

CREATE TABLE IF NOT EXISTS `QuizMYSQL`.`quiz` (
  `idquiz` INT NOT NULL AUTO_INCREMENT,
  `qp_poolid` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `startdate` VARCHAR(45) NOT NULL,
  `enddate` VARCHAR(45) NOT NULL,
  `duration` INT NOT NULL,
  `totalpoints` INT NOT NULL,
  `pointsachieved` INT NOT NULL,
  PRIMARY KEY (`idquiz`),
  INDEX `fk_quiz_qp1_idx` (`qp_poolid` ASC) VISIBLE,
  UNIQUE INDEX `idquiz_UNIQUE` (`idquiz` ASC) VISIBLE,
    FOREIGN KEY (`qp_poolid`)
    REFERENCES `QuizMYSQL`.`qp` (`poolid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



